# Generated by Django 5.2.1 on 2026-02-04 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("neuxo_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=256, null=True)),
                ("first_name", models.CharField(max_length=256, null=True)),
                ("last_name", models.CharField(max_length=256, null=True)),
                ("phone_number", models.CharField(max_length=64, null=True)),
                ("pwd_sha256", models.CharField(max_length=64, null=True)),
                ("email", models.CharField(max_length=128, null=True)),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("VERIFIED", "VERIFIED"),
                            ("VERIFY_FAILED", "VERIFY_FAILED"),
                        ],
                        default="NEW",
                        max_length=128,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Admin", "Admin"), ("User", "User")],
                        default="User",
                        max_length=128,
                    ),
                ),
                ("location", models.CharField(max_length=256, null=True)),
                ("linkedin_cookie", models.TextField(null=True)),
                ("group", models.CharField(max_length=256, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="UserWatchList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("target_guest", models.JSONField(max_length=256, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("time_PIN", models.DateTimeField(default=None, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincompany",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
            options={
                "db_table": "User_WatchList",
            },
        ),
    ]
