# Generated by Django 5.2.1 on 2026-05-24 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userwatchlist_icp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userwatchlist",
            name="ICP",
        ),
        migrations.RemoveField(
            model_name="userwatchlist",
            name="time_PIN",
        ),
    ]
