# Generated by Django 5.2.1 on 2026-05-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_userwatchlist_icp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwatchlist",
            name="time_PIN",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
