# Generated by Django 5.2.1 on 2026-02-04 08:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventsList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("event_url", models.URLField(blank=True, null=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("ticket_key", models.CharField(blank=True, max_length=100, null=True)),
                ("api_id", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=1000, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "event_parent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("event_parent_path", models.URLField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("number_of_company", models.IntegerField(blank=True, null=True)),
                ("number_of_guest", models.IntegerField(blank=True, null=True)),
                ("account", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("event_image", models.TextField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("guest_count", models.IntegerField(blank=True, null=True)),
                ("start_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "Events_List",
            },
        ),
        migrations.CreateModel(
            name="LinkedinCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "DEFAULT_Linkedin_Category",
            },
        ),
        migrations.CreateModel(
            name="LinkedinExcludeCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "DEFAULT_Linkedin_ExcludeCompany",
            },
        ),
        migrations.CreateModel(
            name="LinkedinExcludeKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "DEFAULT_Linkedin_ExcludeKey",
            },
        ),
        migrations.CreateModel(
            name="LinkedinLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "DEFAULT_Linkedin_Location",
            },
        ),
        migrations.CreateModel(
            name="MainEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("event_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "avatar_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("geo_city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "geo_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("geo_region", models.CharField(blank=True, max_length=100, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                (
                    "verified_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "Events_MainEvents",
            },
        ),
        migrations.CreateModel(
            name="ShowingField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_columns", models.CharField(max_length=100)),
                ("is_show", models.TextField(blank=True, null=True)),
                ("can_arrange", models.TextField(blank=True, default="NO", null=True)),
                ("order_by", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                "db_table": "User_Dashboard_ShowingField",
            },
        ),
        migrations.CreateModel(
            name="LinkedinCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "linkedin_uid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "link_twitter",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "linkedin_funding_amt",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "linkedin_lasted_funding_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "organization_type",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "headquarters",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("followers", models.PositiveIntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("labels", models.JSONField(blank=True, default=list, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "is_finding_company",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_crawl", models.CharField(blank=True, max_length=50, null=True)),
                ("is_blacklist", models.BooleanField(default=False, null=True)),
                (
                    "organization_revune_apollo",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignee", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "Linkedin_Companies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="Linkedin_Co_name_c005a9_idx"),
                    models.Index(
                        fields=["industry"], name="Linkedin_Co_industr_e02e51_idx"
                    ),
                    models.Index(
                        fields=["country"], name="Linkedin_Co_country_f70b13_idx"
                    ),
                    models.Index(
                        fields=["category"], name="Linkedin_Co_categor_929b11_idx"
                    ),
                    models.Index(
                        fields=["is_blacklist"], name="Linkedin_Co_is_blac_67d9c0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="Linkedin_Co_created_d85fab_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="Linkedin_Co_updated_629d6f_idx"
                    ),
                    models.Index(
                        fields=["assignee"], name="Linkedin_Co_assigne_3a145e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GuestList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(max_length=100)),
                ("role", models.CharField(blank=True, max_length=300, null=True)),
                ("check_company", models.BooleanField(default=False)),
                (
                    "email_status_emailinfor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "send_by_emailinfor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_activity_emailinfor",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("error_emailinfor", models.TextField(blank=True, null=True)),
                (
                    "last_reply_emailinfor",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("email_input_from_user", models.BooleanField(default=False)),
                ("time_zone", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.eventslist",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincompany",
                    ),
                ),
            ],
            options={
                "db_table": "Events_GuestList",
            },
        ),
        migrations.CreateModel(
            name="LinkedinJobLabels",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_pick_gen_ai", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincategory",
                    ),
                ),
            ],
            options={
                "db_table": "DEFAULT_Linkedin_JobLabels",
            },
        ),
        migrations.AddField(
            model_name="eventslist",
            name="main_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="neuxo_backend.mainevents",
            ),
        ),
        migrations.CreateModel(
            name="MasterCompanies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trigger", models.JSONField(blank=True, default=list, null=True)),
                ("contact", models.BooleanField(default=False)),
                ("funding_amount", models.TextField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "trigger_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "lst_email_contact",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("user_reach_out", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincompany",
                    ),
                ),
            ],
            options={
                "db_table": "Companies_Master",
            },
        ),
    ]
