# Generated by Django 5.2.1 on 2026-02-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("neuxo_backend", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="showingfield",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
            ),
        ),
        migrations.AddIndex(
            model_name="guestlist",
            index=models.Index(
                fields=["created_at"], name="Events_Gues_created_214225_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestlist",
            index=models.Index(
                fields=["company"], name="Events_Gues_company_2c6378_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestlist",
            index=models.Index(
                fields=["email_status_emailinfor"],
                name="Events_Gues_email_s_d1d7a1_idx",
            ),
        ),
    ]
