# Generated by Django 5.2.1 on 2026-02-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0003_document_linkedincompany_note_of_user_mailappaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedincompany",
            name="lst_email_contact",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="linkedincompany",
            name="user_reach_out",
            field=models.TextField(blank=True, null=True),
        ),
    ]
