# Generated by Django 5.2.1 on 2026-02-11 03:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0004_linkedincompany_lst_email_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedinJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.TextField(blank=True, default="active", null=True)),
                ("last_check", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincompany",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedinjoblabels",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedinlocation",
                    ),
                ),
            ],
            options={
                "db_table": "Linkedin_Jobs",
                "indexes": [
                    models.Index(fields=["created_at"], name="job_created_at_idx"),
                    models.Index(
                        fields=["company", "last_check"],
                        name="job_company_lastcheck_idx",
                    ),
                    models.Index(fields=["linkedin_url"], name="job_linkedin_url_idx"),
                ],
            },
        ),
    ]
