# Generated by Django 5.2.1 on 2026-02-11 03:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0005_linkedinjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("SUB_DOMAIN", "SUB_DOMAIN"),
                            ("LINKEDIN", "LINKEDIN"),
                            ("TWITTER", "TWITTER"),
                            ("EVENT", "EVENT"),
                            ("HIRING", "HIRING"),
                            ("NEWS", "NEWS"),
                            ("FUNDING", "FUNDING"),
                            ("JOB_CHANGE", "JOB_CHANGE"),
                        ],
                    ),
                ),
                ("reference_id", models.TextField(blank=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("post_url", models.TextField(blank=True, null=True)),
                ("time_post", models.DateTimeField(default=django.utils.timezone.now)),
                ("guest_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_send", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincompany",
                    ),
                ),
            ],
            options={
                "db_table": "Notification",
            },
        ),
    ]
