# Generated by Django 5.2.1 on 2026-02-25 09:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0006_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyFunding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("round", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount", models.CharField(blank=True, max_length=100, null=True)),
                ("category", models.CharField(blank=True, max_length=500, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("project_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "linkedin_uid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincompany",
                    ),
                ),
            ],
            options={
                "db_table": "Funding",
                "indexes": [
                    models.Index(fields=["name"], name="Funding_name_b7ecf2_idx"),
                    models.Index(
                        fields=["updated_at"], name="Funding_updated_1880e9_idx"
                    ),
                ],
            },
        ),
    ]
