# Generated by Django 5.2.1 on 2026-02-25 15:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0007_companyfunding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClutchReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reviewer_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reviewer_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client_size",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("services", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "project_size",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_length",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("project_description", models.TextField(blank=True, null=True)),
                ("background", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "description_company_outsource",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "services_company_outsource",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincompany",
                    ),
                ),
            ],
            options={
                "db_table": "Clutch_Review",
                "indexes": [
                    models.Index(
                        fields=["company"], name="Clutch_Revi_company_d8cde0_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="Clutch_Revi_updated_c1df14_idx"
                    ),
                ],
            },
        ),
    ]
