# Generated by Django 5.2.1 on 2026-02-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0008_clutchreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedincompany",
            name="website",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
