# Generated by Django 5.2.1 on 2026-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0009_alter_linkedincompany_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clutchreview",
            name="website_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
