# Generated by Django 5.2.1 on 2026-03-01 09:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0010_alter_clutchreview_website_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedinPersonalEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("avatar_linkedin_url", models.TextField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=200, null=True)),
                ("twitter_summary", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("is_update", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("urn", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedincompany",
                    ),
                ),
            ],
            options={
                "db_table": "Linkedin_Peoples",
            },
        ),
        migrations.CreateModel(
            name="PersonalEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedinpersonalemail",
                    ),
                ),
            ],
            options={
                "db_table": "Personal_Email",
            },
        ),
        migrations.CreateModel(
            name="PersonalExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "linkedin_company_id",
                    models.TextField(blank=True, max_length=50, null=True),
                ),
                ("linkedin_company_url", models.TextField(blank=True, null=True)),
                ("linkedin_company_logo", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("company_name", models.TextField(blank=True, null=True)),
                ("time_period", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.linkedinpersonalemail",
                    ),
                ),
            ],
            options={
                "db_table": "Linkedin_Personal_Experience",
            },
        ),
    ]
