# Generated by Django 5.2.1 on 2026-03-21 03:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neuxo_backend",
            "0012_listicp_historygenai_mentions_mentionslinkedin_and_more",
        ),
        ("users", "0002_userwatchlist_icp"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailGenHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_id", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("step_number", models.IntegerField(default=0)),
                ("status", models.TextField(default="RUNNING")),
                ("subject", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_prompt", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Mail_Gen_History",
            },
        ),
        migrations.CreateModel(
            name="MailTemplateBimonthly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("link_and_images", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("order_of_mail", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "Mail_Template_Bimonthly",
            },
        ),
        migrations.CreateModel(
            name="NewsFeedSkyNet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("link", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "News_Feed_SkyNet",
            },
        ),
        migrations.CreateModel(
            name="ReportEmailDimTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_date", models.DateField()),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("quarter", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "DIM_Report_Email_Time",
            },
        ),
        migrations.CreateModel(
            name="SalesPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "User_Sales",
            },
        ),
        migrations.CreateModel(
            name="CustomFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filter_name", models.TextField(blank=True, null=True)),
                ("filter", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "User_Custom_Filter",
            },
        ),
        migrations.CreateModel(
            name="EmailHistoryNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("main_target_email", models.TextField()),
                ("user_note", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.TextField(
                        choices=[
                            ("HIGH", "HIGH"),
                            ("MEDIUM", "MEDIUM"),
                            ("LOW", "LOW"),
                        ],
                        default="MEDIUM",
                    ),
                ),
                ("is_replied", models.BooleanField(default=False)),
                (
                    "follow_up_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
            options={
                "db_table": "User_Email_History_Note",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_name",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "template_subject",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("template_content", models.TextField(blank=True, null=True)),
                ("attachments", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
            options={
                "db_table": "Email_Template",
            },
        ),
        migrations.CreateModel(
            name="MailHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mail_send", models.TextField(blank=True, max_length=300, null=True)),
                (
                    "mail_recieved",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("time_send", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True, null=True)),
                ("subject", models.TextField(blank=True, null=True)),
                (
                    "main_target_mail",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "name_target_mail",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("html_mail_content", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("id_attachment", models.TextField(blank=True, null=True)),
                ("message_id", models.TextField(blank=True, null=True)),
                ("status_mail", models.TextField(blank=True, null=True)),
                ("email_ref_first_id", models.TextField(blank=True, null=True)),
                ("email_reply_id", models.TextField(blank=True, null=True)),
                ("campaign_id", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "User_Mail_History",
            },
        ),
        migrations.CreateModel(
            name="EmailTracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tracking_id", models.CharField(max_length=100, unique=True)),
                ("message_id", models.CharField(blank=True, max_length=255, null=True)),
                ("opened", models.BooleanField(default=False)),
                ("opened_count", models.IntegerField(default=0)),
                ("first_opened_at", models.DateTimeField(blank=True, null=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "location_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mail_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.mailhistory",
                    ),
                ),
            ],
            options={
                "db_table": "User_Email_Tracker",
            },
        ),
        migrations.CreateModel(
            name="FactReportEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("main_target_email", models.TextField()),
                ("new_emails_sent", models.IntegerField(default=0)),
                ("emails_received", models.IntegerField(default=0)),
                ("is_replied", models.BooleanField(default=False)),
                ("total_email_sent", models.IntegerField(default=0)),
                ("followup_1_count", models.IntegerField(default=0)),
                ("followup_2_count", models.IntegerField(default=0)),
                ("followup_3_count", models.IntegerField(default=0)),
                ("followup_4_count", models.IntegerField(default=0)),
                ("followup_5_count", models.IntegerField(default=0)),
                ("followup_5plus_count", models.IntegerField(default=0)),
                ("time_send", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
                (
                    "dim_time",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.reportemaildimtime",
                    ),
                ),
            ],
            options={
                "db_table": "FACT_Report_Email",
            },
        ),
        migrations.CreateModel(
            name="SequenceEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence_name",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "email_targets",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "sequence_status",
                    models.TextField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        default="PENDING",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign_name",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("source", models.TextField(blank=True, max_length=500, null=True)),
                ("event_id", models.TextField(blank=True, max_length=500, null=True)),
                ("num_email_sent", models.IntegerField(default=0, null=True)),
                ("num_email_replied", models.IntegerField(default=0, null=True)),
                ("num_email_opened", models.IntegerField(default=0, null=True)),
                ("enable_bimonthly_send", models.BooleanField(default=False)),
                ("max_email_bimonthly", models.IntegerField(null=True)),
                ("user_hot_trigger", models.BooleanField(default=False)),
                (
                    "hot_trigger_condition",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("day_start_bimonthly", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
            options={
                "db_table": "Automate_Email",
            },
        ),
        migrations.CreateModel(
            name="SequenceEmailStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_number", models.IntegerField(default=0)),
                ("status", models.TextField(default="PENDING")),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_paused", models.BooleanField(default=False)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.sequenceemail",
                    ),
                ),
            ],
            options={
                "db_table": "Automate_Email_Step",
            },
        ),
        migrations.CreateModel(
            name="SequenceEmailStepHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_sender",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("email_target", models.TextField(max_length=300)),
                ("subject", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("email_prompt", models.TextField(blank=True, null=True)),
                (
                    "email_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.sequenceemailstep",
                    ),
                ),
            ],
            options={
                "db_table": "Automate_Email_Step_History",
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signature_html", models.TextField()),
                ("signature_name", models.TextField(default="Default")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "user_gmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neuxo_backend.mailappaccount",
                    ),
                ),
            ],
            options={
                "db_table": "Signature",
            },
        ),
        migrations.AddField(
            model_name="sequenceemail",
            name="signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="neuxo_backend.signature",
            ),
        ),
        migrations.CreateModel(
            name="EmailOpenedNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict, null=True)),
                ("last_data", models.JSONField(blank=True, default=dict, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_fetched", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
                (
                    "email_tracker",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opened_notification",
                        to="neuxo_backend.emailtracker",
                    ),
                ),
            ],
            options={
                "db_table": "Email_Opened_Notification",
                "indexes": [
                    models.Index(
                        fields=["user", "is_fetched"],
                        name="Email_Opene_user_id_76fda9_idx",
                    ),
                    models.Index(
                        fields=["email_tracker"], name="Email_Opene_email_t_2092e0_idx"
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="Email_Opene_user_id_3d7618_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="emailtracker",
            index=models.Index(
                fields=["tracking_id"], name="User_Email__trackin_9e18c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtracker",
            index=models.Index(
                fields=["message_id"], name="User_Email__message_a402f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtracker",
            index=models.Index(fields=["opened"], name="User_Email__opened_f85ba5_idx"),
        ),
        migrations.AddIndex(
            model_name="emailtracker",
            index=models.Index(
                fields=["created_at"], name="User_Email__created_a5a174_idx"
            ),
        ),
    ]
