# Generated by Django 5.2.1 on 2026-04-03 07:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuxo_backend', '0013_mailgenhistory_mailtemplatebimonthly_newsfeedskynet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApifyToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_time_available', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=100)),
            ],
            options={
                'db_table': 'Apify_Token',
            },
        ),
    ]
