# Generated by Django 5.2.1 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuxo_backend", "0014_apifytoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedinpersonalemail",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="linkedinpersonalemail",
            name="education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="company_universal_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="duration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="employment_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="end_date_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="end_month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="experience_group_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="source_profile_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="start_date_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="start_month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalexperience",
            name="workplace_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
