# Generated by Django 5.2.1 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuxo_backend", "0015_profile_enrichment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentionslinkedin",
            name="attributes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="author_followers_count",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="author_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="author_profile_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="author_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="author_urn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="images",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="input_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="num_comments",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="num_likes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="num_shares",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="post_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="post_urn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="posted_at_iso",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="posted_at_timestamp",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="share_urn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentionslinkedin",
            name="time_since_posted",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
