# Generated by Django 5.2.1 on 2026-04-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0017_apifytoken_gmail_apifytoken_pass_gmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyfunding",
            name="news_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
