# Generated by Django 5.2.1 on 2026-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0018_companyfunding_news_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedinpersonalemail",
            name="role",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
