# Generated by Django 5.2.1 on 2026-05-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuxo_backend", "0019_alter_linkedinpersonalemail_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mastercompanies",
            old_name="score",
            new_name="recommendation_score",
        ),
        migrations.AddField(
            model_name="mastercompanies",
            name="total_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mastercompanies",
            name="trigger_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
