# Generated by Django 5.2.1 on 2026-05-24 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "neuxo_backend",
            "0020_rename_score_mastercompanies_recommendation_score_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalesPerson",
        ),
    ]
