"""
Django settings for neuxo project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote

from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _build_redis_url(
    host: str | None,
    port: str | None,
    db: str | None,
    password: str | None = None,
) -> str:
    host = host or "127.0.0.1"
    port = port or "6379"
    db = db or "0"
    if password:
        return f"redis://:{quote(password)}@{host}:{port}/{db}"
    return f"redis://{host}:{port}/{db}"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SCHEMA_URL = "/api/docs/schema/"
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-t$+9h!zwnw!=0gxd6s35fk643&@wb5@n91xpv+ll%tx!+d8hrt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "neuxo_backend",
    "users",
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "django_crontab",
    "channels",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "neuxo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "neuxo.wsgi.application"
ASGI_APPLICATION = "neuxo.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_NAME"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "connect_timeout": 5,
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

STATIC_ROOT = os.path.join(
    BASE_DIR, "staticfiles"
)  # Changed to 'staticfiles' to avoid conflict
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
if not os.path.exists(os.path.join(BASE_DIR, "static")):
    os.makedirs(os.path.join(BASE_DIR, "static"))
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    # other DRF settings here
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
}

SPECTACULAR_SETTINGS = {
    "DESCRIPTION": """This is a SaleIQ docs api. You can find more about the API at [SaleIQ API]().""",
    "TITLE": "SALE-IQ API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication"
    ],
    "CONTACT": {"name": "Phong Nguyen", "email": "", "url": ""},
    "LICENSE": {"name": "MIT", "url": "https://opensource.org/licenses/MIT"},
    "TAGS": [
        {
            "name": "Authentication",
            "description": "RCVR user Basic Authentication to get access token and refresh token when call Sign-in API then use access token to call other APIs",
        },
        {"name": "User", "description": "User operations"},
    ],
    # Adding server configuration for Nginx proxying
    "SERVERS": [
        {"url": "/", "description": "API Local"},
        {"url": "/api", "description": "API Server"},
    ],
    # Schema handler configuration
    "SCHEMA_PATH_PREFIX": "/api",
    "SCHEMA_PATH_PREFIX_INSERT": False,
    "APPEND_COMPONENTS": {},
}


SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "api_key": {"type": "apiKey", "in": "header", "name": "Authorization"}
    },
    "DOC_EXPANSION": None,
    "APIS_SORTER": None,
    "OPERATIONS_SORTER": None,
    "JSON_EDITOR": False,
    "SHOW_REQUEST_HEADERS": False,
    "SUPPORTED_SUBMIT_METHODS": ["get", "post", "put", "delete", "patch"],
    "VALIDATOR_URL": "",
}

REDOC_SETTINGS = {
    "LAZY_RENDERING": False,
    "HIDE_HOSTNAME": False,
    "EXPAND_RESPONSES": "all",
    "PATH_IN_MIDDLE_PANEL": False,
    "SCROLL_Y_OFFSET": 50,
    "SCROLL_X_OFFSET": 50,
    "SHOW_EXTENSIONS": False,
    "SHOW_COMMON_EXTENSIONS": False,
    "EXTENSIONS": [],
    "REQUIRED_PROPS_FIRST": False,
    "SORT_PROPS_ALPHABETICALLY": False,
    "NO_AUTO_AUTH": False,
    "HIDE_DOWNLOAD_BUTTON": False,
    "HIDE_TOC": False,
    "HIDE_NAVIGATION_BAR": False,
    "NAVIGATION_BAR_BACKGROUND": "#ffffff",
    "NAVIGATION_BAR_COLOR": "#000000",
    "FOOTER": "",
    "FOOTER_MODE": "sticky",
    "DISABLE_SEARCH": False,
    "DISABLE_FILTER": False,
    "DISABLE_SORT": False,
    "THEME": "dark",
    "EXPAND_DEFAULT_SERVER_VARIABLES": False,
    "RESPONSES_TRAY": False,
}
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": _build_redis_url(
            os.getenv("REDIS_HOST"),
            os.getenv("REDIS_PORT"),
            os.getenv("REDIS_DB"),
        ),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": os.getenv("REDIS_PASSWORD"),
        },
    }
}

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    _build_redis_url(
        os.getenv("REDIS_HOST"),
        os.getenv("REDIS_PORT"),
        os.getenv("REDIS_DB", "1"),
    ),
)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "1200"))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "900"))
CELERY_WORKER_PREFETCH_MULTIPLIER = int(
    os.getenv("CELERY_WORKER_PREFETCH_MULTIPLIER", "1")
)
CELERY_TASK_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_EMAIL_CRAWL_BATCH_SIZE = int(os.getenv("CELERY_EMAIL_CRAWL_BATCH_SIZE", "50"))
CELERY_EMAIL_CRAWL_COUNTDOWN = int(os.getenv("CELERY_EMAIL_CRAWL_COUNTDOWN", "2"))

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#         },
#     },
#     "root": {
#         "handlers": ["console"],
#         "level": "CRITICAL",
#     },
#     "loggers": {
#         "email_sender": {
#             "handlers": ["console"],
#             "level": "INFO",
#             "propagate": False,
#         },
#     },
# }

# Use this setting locally if your redis does not require password
# CHANNEL_LAYERS = {
#     'default': {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [(
#                 os.getenv("REDIS_HOST", "127.0.0.1"),
#                 int(os.getenv("REDIS_PORT", 6379))
#             )],
#         },
#     },
# }

# # Use this setting if your redis requires password
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                f"redis://:{os.getenv('REDIS_HOST')}:{os.getenv('REDIS_PORT')}/0"
            ],
        },
    },
}

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#         'channels': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }


CORS_ALLOWED_ORIGINS = [
  "http://localhost:3001",
]

CORS_ALLOW_CREDENTIALS = True  # nếu login dùng cookie/session
CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOW_METHODS = ["GET","POST","PUT","PATCH","DELETE","OPTIONS"]

APPEND_SLASH = False
